FROM ubuntu
RUN apt-get update && apt-get install -y ttyd
RUN apt-get update 
RUN apt-get install openjdk-17-jdk -y
RUN apt-get install openjdk-17-jre -y
RUN apt-get install maven -y

ENTRYPOINT  /bin/bash
